[package]
name = "av1an-cli"
version = "0.3.2"
authors = ["Zen <master_of_zen@protonmail.com>"]
description = """
Cross-platform command-line AV1 / VP9 / HEVC / H264 encoding framework with per scene quality encoding [Command line library]
"""
repository = "https://github.com/master-of-zen/Av1an"
keywords = ["video"]
categories = ["command-line-utilities"]
license = "GPL-3.0"
rust-version = "1.59"
edition = "2021"

[dependencies]
atty = "0.2.14"
clap = { version = "4.0.8", features = ["derive"] }
shlex = "1.1.0"
path_abs = "0.5.1"
anyhow = "1.0.65"
av1an-core = { path = "../av1an-core", version = "0.3.1" }
thiserror = "1.0.37"
once_cell = "1.15.0"
ansi_term = "0.12.1"

[dependencies.flexi_logger]
version = "0.23.3"
default-features = false
features = ["colors", "use_chrono_for_offset"]

[build-dependencies.vergen]
version = "7.4.2"
default-features = false
features = ["git", "build", "rustc", "cargo"]

[dependencies.ffmpeg]
package = "ffmpeg-next"
version = "5.1.1"

[features]
ffmpeg_static = ["ffmpeg/static", "ffmpeg/build"]
