[package]
name = "av1an-core"
version = "0.3.2"
rust-version = "1.59"
edition = "2021"
authors = ["Zen <master_of_zen@protonmail.com>"]
description = """
Cross-platform command-line AV1 / VP9 / HEVC / H264 encoding framework with per scene quality encoding [Core library]
"""
repository = "https://github.com/master-of-zen/Av1an"
keywords = ["video"]
categories = ["command-line-utilities"]
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
arrayvec = "0.7.2"
atty = "0.2.14"
av-format = "0.3.1"
av-ivf = "0.2.2"
av1-grain = { version = "0.2.0", default-features = false, features = [
  "create",
] }
memchr = "2.5.0"
anyhow = "1.0.65"
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sysinfo = "0.26.4"
splines = "4.1.1"
indicatif = "=0.17.0-rc.4"
once_cell = "1.15.0"
strum = { version = "0.24.1", features = ["derive"] }
itertools = "0.10.5"
which = "4.3.0"
strsim = "0.10.0"
crossbeam-channel = "0.5.6"
crossbeam-utils = "0.8.12"
textwrap = "0.15.1"
path_abs = "0.5.1"
av-scenechange = { version = "0.7.2", default-features = false }
y4m = "0.7.0"
thiserror = "1.0.37"
paste = "1.0.9"
simdutf8 = "0.1.4"
parking_lot = "0.12.1"
cfg-if = "1.0.0"
nom = "7.1.1"
# TODO: move all of this CLI stuff to av1an-cli
ansi_term = "0.12.1"

# TODO: https://github.com/elast0ny/affinity/issues/2
# update this when macos support is implemented
[target.'cfg(any(target_os = "linux", target_os = "windows"))'.dependencies]
affinity = "0.1.2"

[dependencies.smallvec]
version = "1.10.0"
default-features = false
features = ["const_generics", "const_new", "union"]

[dependencies.ffmpeg]
package = "ffmpeg-next"
version = "5.1.1"

[dependencies.plotters]
version = "0.3.4"
default-features = false
features = ["svg_backend", "line_series"]

[dependencies.vapoursynth]
version = "0.4.0"
features = ["vsscript-functions", "vapoursynth-functions"]

[dependencies.tokio]
version = "1"
features = ["rt", "process", "io-util"]

[dependencies.dashmap]
version = "5.4.0"
features = ["serde"]

[dev-dependencies]
quickcheck = { version = "1.0.3", default-features = false }
quickcheck_macros = "1"

[features]
ffmpeg_static = ["ffmpeg/static", "ffmpeg/build"]
vapoursynth_new_api = [
  "vapoursynth/vapoursynth-api-32",
  "vapoursynth/vsscript-api-31",
]
